# Generated by Django 3.2.16 on 2023-11-18 01:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20231117_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='Start writing your content here...'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='Enter a brief description here...', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='post-<function uuid4 at 0x0000021C6E66BBA0>', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='New Post', max_length=255),
        ),
    ]
