# Generated by Django 3.2.16 on 2023-11-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20231117_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='post-d763c17f-c74f-407d-8928-18d6fc998f97', max_length=255, unique=True),
        ),
    ]
